name: Main CI WorkFlow
on:
  push:
    branches:
      - main
    tags:
  pull_request:

jobs:
  verify:
    name: Verify Project
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: go get -v -t -d ./...

      - name: Test
        run: go test -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
